### ISSUE TITLE
Consider deprecating library since @mswjs/source is released

### ISSUE THREAD

**Issue by weyert** [Tapico/tapico-msw-webarchive#86]
The last few years I have been working on `@mswjs/source`-package and most of the features of `@tapico/msw-webarchive` are covered by this package. 

I would like to suggest to deprecate this package and suggest to using this new package.

@ctuckz @kettanaito @dwjohnston Please note

**Comment by kettanaito** [comment]
I'm grateful for your support over the years! I think this makes the most sense for users. So happy to join forces and keep maintaining msw-webarchive in a shape of Source! :tada:

**Comment by ctuckz** [comment]
Congrats on the release! Excited to try out the new package

**Comment by weyert** [comment]
@ctuckz did you had a chance to try it out? Any functionality missing for you?

**Comment by ctuckz** [comment]
hey @weyert! We're working on migrating one of our clients (our main web application actually) over since we found that Source fixed some issues we were having getting msw-webarchive to work with playwright-msw. So far from what I've heard the migration has gone pretty smoothly. The person working on it mentioned an issue with our graphql endpoints, but they were able to resolve it for now by excluding them with the mapEntry function. I need to chat with him some more to understand what the issue was. If it's due to a bug or missing functionality we'll open up an issue in source with more details!

**Comment by weyert** [comment]
Thank you @ctuckz. Happy to hear you are enjoying using `@mswjs/source` so far :)
